version: "3"
services:
    postgres:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: Datapilot
            POSTGRES_DB: datapilot
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ../../.pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

    api:
        image: alpine


#    coreui:
#        build:
#            context: ./coreui
#        ports:
#            - "18080:80"

